# Generated by Django 4.0.4 on 2022-05-12 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='', max_length=100)),
                ('country', models.CharField(default='', max_length=50)),
                ('locale', models.CharField(default='en-US', max_length=5)),
                ('gender', models.CharField(default='Female', max_length=6)),
                ('voice_name', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
